### ISSUE TITLE
issue formatting disks createparentdisks.ps1

### ISSUE THREAD

**Issue by MarcelRond** [Microsoft/WSLab#169]
When I run the second script, I get an error when the script tries to format the volume. 
"Format-Volume : Invalid Parameter". See screenshot. I a running win10 enterprise 1803 and using Win2016 eval ISO ver. 14393.

![capture](https://user-images.githubusercontent.com/31615351/41784098-361652be-762e-11e8-8626-d00cc9eec1a4.PNG)

Log entry:
Format-Volume : Invalid Parameter
Activity ID: {c7bb7eb5-96a7-41a0-a059-0e02b046b6fa}
At C:\S2DVMs\tools\convert-windowsimage.ps1:1935 char:41
+ ... temVolume = Format-Volume -Partition $systemPartition -FileSystem FAT ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (StorageWMI:ROOT/Microsoft/...age/MSFT_Volume) [Format-Volume], CimExcept
ion
    + FullyQualifiedErrorId : StorageWMI 5,Format-Volume
Format-Volume : Invalid Parameter
Activity ID: {c7bb7eb5-96a7-41a0-a059-0e02b046b6fa}
At C:\S2DVMs\tools\convert-windowsimage.ps1:1935 char:41
+ ... temVolume = Format-Volume -Partition $systemPartition -FileSystem FAT ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (StorageWMI:ROOT/Microsoft/...age/MSFT_Volume) [Format-Volume], CimExce
   ption
    + FullyQualifiedErrorId : StorageWMI 5,Format-Volume

**Comment by jaromirk** [comment]
Hello Marcel, this part is purely driven by convert-windowsimage https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/master/hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.ps1 . Can you try different iso? Mine works well, strange... I have win10 1803 enterprise too....

**Comment by MarcelRond** [comment]
Tried a different ISO from the VLSC Portal. Still the same issue. I disabled the virusscanner. Still the same issue.
The vhd files get created and I get a Windows pop-up that the volume needs to be formatted, right after the error from the script.  When I click "Format" The volume cannot be formatted.

**Comment by jaromirk** [comment]
The format window can be ignored. The convert-windowsimage creates vhd, mounts it (and windows notices emty volume, thats why the window with format), then it should format it and copy windows files from wim. There must be somethimg in your system then, convert-windowsimage did not change for 2 yearsm

**Comment by jaromirk** [comment]
@pronichkin , do you have any idea why format would fail? Did you see this error before?

**Comment by jaromirk** [comment]
@MarcelRond , still having issues?

**Comment by MarcelRond** [comment]
Hi Jaromir,
Thanks for your interest.
Yes, still have the issue.
Don’t know whats is wrong. I agree, I think it must be something wrong in my system.
But if you have advise, I am listening ☺
Thanks for your effort.

Met vriendelijke groet, Best regards,

Marcel Rond
Senior Technisch Specialist

SPS ( Continuïteit in IT
Buitenomweg 17 | 2811 BM Reeuwijk
T +31182-302200 |  F +31182-302323
Marcel.Rond@sps.nl<mailto:Marcel.Rond@sps.nl> | www.sps.nl<http://www.sps.nl> |   sps twitter <https://twitter.com/#!/spsholding>  |  sps linkedin<http://www.linkedin.com/company/sps-it>

**Comment by DarrylvanderPeijl** [comment]
@MarcelRond I had the same issue once. Try creating the parentdisks on a different system and it will work.

**Comment by jaromirk** [comment]
Closing issue.
