### ISSUE TITLE
Server CORE as host and issue at mounting ISO

### ISSUE THREAD

**Issue by m12net** [Microsoft/WSLab#184]
Hi,

I got a hands on physical server for my Home Lab and installed 17713 CORE edition. I wanted to use it as starting point for testing some of your labs, but I came across error, which throws me out of powershell and generates following output:
"Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt."
![screenshot](https://user-images.githubusercontent.com/41618324/43128524-7f77c844-8f32-11e8-88a5-0080a35dbe28.png)

This happens, when script should ask me for ISO.
To avoid this, I changed Labconfig and pushed in Server ISO parameter, but it seems that CORE detection mechanism is not working.

Regards,
Matjaž

**Comment by jaromirk** [comment]
Hmm, it looks like something from this piece of code is not working https://github.com/Microsoft/WSLab/blob/master/Scripts/3_Deploy.ps1#L804-L811

**Comment by jaromirk** [comment]
LOL... The piece of code is working, but it should be in 2_createparentdisks, and not 3_deploy! I should stop writing scripts at night :). Will fix it...

**Comment by jaromirk** [comment]
I committed it to dev. Please test this 2_createparentdisks https://raw.githubusercontent.com/Microsoft/WSLab/dev/Scripts/2_CreateParentDisks.ps1

**Comment by m12net** [comment]
Detection works now.


Thank you for rapid response.
