### ISSUE TITLE
Azure ARM templates for WSLab are not working

### ISSUE THREAD

**Issue by jaromirk** [Microsoft/WSLab#195]
DSC is not applied. I need more time/or someone experienced. Anyone want's to take a look into json? https://github.com/Microsoft/WSLab/tree/dev/Scenarios/Running%20WSLab%20in%20Azure

**Comment by MS-MatthewWalker** [comment]
I can work on it, you have to add the DSC extension into the the VM template for DSC to work in Azure

**Comment by jaromirk** [comment]
I dunno what issue was, but it was solved by adding automation account in the same region as VM. Now it works even without that automation account. Weird.
