### ISSUE TITLE
SCVMM - Installing ADK(1709) gets stuck - how to install it manually

### ISSUE THREAD

**Issue by Marcel-Uni** [Microsoft/WSLab#235]
Hello Jaromirk.

I was tasked by the chair of my universtity to evaluate S2D with a 3 Server Cluster and if it should be managaged using SCVMM (Version 1801) or if SCVMM is not necessary.
So I downloaded the scripts and Labconfig for this scenario from github. I added InstallSCVMM='Yes' in the Labconfig and skipped creation of Management and WDS (since I wanted to run everything from DC).
The Scripts work fine until in the create_parent_disk script executes the  install_ADK part (Version 1709). This stept always gets stuck for me. (I tried it 4 times)
--> See image 1 

I gave the install script more than one hour.
Then I logged in to DC maually. I opened the Tools-Disk and started the ADK setup manually.
--> See image 2

After the install finished I checked if the files had been installed into the right directory.
--> See image 3

Now I restarted DC manually to continue with the main Script (create_Parent_Disks) which should now install SCVMM. 
--> See image 4

The main script tells me that SCVMM was installed after 1.54 Minutes.
--> See image 5

Now I executed the Deploy-Script which worked fine.
-->See image 6 

I connected to DC but SCVMM is nowhere to be found even though all prerequesites (SQL Server 2017 is running and ADK is installed)  are given. 
--> See image 7

So after several tries I decided to also install SCVMM manually as well. 
--> See image 8

But I get stuck at configuring the datebase connection, since the admin login credentials are rejected. 
I tried LabAdmin, Administrator, VMM_SA, SQL_SA  with the password LS1setup! but everything was rejected. I couldn't find any other login credentials within your scripts.
-->See image 9

I have two main questions.

Can you tell me which credetials are supposed to be used in image 9, so that the following scenario script works?

I saw that there was an [ issue](https://github.com/Microsoft/WSLab/issues/141) before with the install_adk script. Did you maybe find out why it gets stuck? Maybe my manual installation of ADK causes issues with the following SCVMM setup.

Regards
Marcel

PS: Sorry that the screenshots partly contain german text, but I'm sure you know the console output by heart anyway.
Image 1
![1-adk-install-script-stuck](https://user-images.githubusercontent.com/45870779/49992728-2fa6e480-ff85-11e8-9454-5b5d1916b452.PNG)
Image 2
![2-adk-on-dc-manual-install](https://user-images.githubusercontent.com/45870779/49992729-2fa6e480-ff85-11e8-96fe-3c8110900db2.PNG)
Image 3
![3-adk-on-dc-installed](https://user-images.githubusercontent.com/45870779/49992730-2fa6e480-ff85-11e8-8b5b-459fff73a8ba.PNG)
Image 4
![4-dc-manual-restart](https://user-images.githubusercontent.com/45870779/49992731-2fa6e480-ff85-11e8-98d5-2cf5e58f7760.PNG)
Image 5
![5-vmm-install-finished-fast](https://user-images.githubusercontent.com/45870779/49992732-2fa6e480-ff85-11e8-98fb-9884d1ddffce.PNG)
Image 6
![6-deploy](https://user-images.githubusercontent.com/45870779/49992733-303f7b00-ff85-11e8-9ba2-737988a43e51.PNG)
Image 7
![7-scvmm-is-not-installed](https://user-images.githubusercontent.com/45870779/49992734-303f7b00-ff85-11e8-9962-c6e3b5b9ca53.PNG)
Image 8
![8-scvmm-manual-setup](https://user-images.githubusercontent.com/45870779/49992735-303f7b00-ff85-11e8-880b-8f21ddc30c95.PNG)
Image 9
![9-scvmm-manual-setup-db-connection](https://user-images.githubusercontent.com/45870779/49992736-303f7b00-ff85-11e8-865f-f9eac5934372.PNG)

**Comment by jaromirk** [comment]
Send me mail with your phone. I'll call you 😉 Jaromirk@microsoft.com

**Comment by jaromirk** [comment]
I tested 1803 ADK and that worked for me. Did you see aka.ms/wslabvideos ? Scvmm install is covered there

**Comment by jaromirk** [comment]
I updated install files to support 1809 and gave a try with that. My config is Win10 RS5, VMs were created with Windows Server 2016 + latest CU, ADK and ADKwinPE 1809, SCVMM 1801+1807update, SQL 2017 and all seems to work fine!

I tried even Bare metal deployment scenario, and ADK works well! 
![image](https://user-images.githubusercontent.com/9829838/50255321-af073e80-03f1-11e9-801f-5a6c1b7639ca.png)

**Comment by Marcel-Uni** [comment]
Hello Jaromir,


I tried it again last Thursday with the updated scripts and with adk 1809.


The createParentDisk script freezed again at the installadk step just like your colleague said in the mail last Friday. When I logged into the virtual DC and executed the adk script manually it installed adk+PE successfully. BUT even though I was running powershell as admin on DC I had to confirm the “I’m aware that scripts from the internet could harm my computer” prompt. Maybe this causes the main script to freeze. After restarting DC I still couldn’t install SCVMM. Neither with the final part of the create parent disk script, nor manually with the 3-scvmm script on the DC tools disk.


Short: no, sadly I was unable to succeed.



The computers at my university are turned of until next year due to power grid maintenance anyways so I can’t test anything right now.


Do you think my host being winServer2016 instead of WIN10 might be the reason?


Regards

Marcel

Am 26.12.2018 um 11:27 schrieb Jaromir Kaspar <notifications@github.com<mailto:notifications@github.com>>:


Marcel, did you succeed?

**Comment by jaromirk** [comment]
Hmm, it sounds like execution policy to me. Let me change the script that it will change execution policy before running that script for ADK install. I'll do it once I get to my PC as it's very simple change...

**Comment by jaromirk** [comment]
OK, so I added execution policy change into scripts. Give it a try and let me know. THX!

**Comment by Marcel-Uni** [comment]
Hello Jaromir,
I tried it again with the added execution policy, but the ADK install got stuck again.

Sadly I was given other tasks at my university job for now which will keep me busy for the next months, so I’m sorry to tell you that I won’t be able to focus on your virtual lab scripts and provide feedback if it’s now working or not.

Thanks a lot for your efforts to get it running for me.

Regards
Marcel

Am 27.12.2018 um 12:54 schrieb Jaromir Kaspar <notifications@github.com<mailto:notifications@github.com>>:


OK, so I added execution policy change into scripts. Give it a try and let me know. THX!

**Comment by jaromirk** [comment]
No worries Marcel,
sorry for complications. Mine setup works well (Win 10 RS5, Win 2019 as guest, …) it's now hydrating and it looks like all works well for me. Weird...
![image](https://user-images.githubusercontent.com/9829838/50953776-b4b5e880-14b4-11e9-8cbd-3a2e07db970b.png)

**Comment by jaromirk** [comment]
Another option would be to import DC manually, install all inside and just shut it down, remove from Hyper-V and restore DC vm files from zip (in folder where DC lives).

**Comment by jaromirk** [comment]
It looks like only Windows Server 2016 is affected. In my Win10 machine all works well. I tried it in Windows Server 2016 and it did not succeed.

**Comment by Marcel-Uni** [comment]
Hello Jaromir,


it's me again.


I just now had time to try and run the Scripts again. I newly set up the host PC as win 10 rs5 as you suggested.


For the DC I used an WinServer2019 ISO and on another attempt WinServer2016. Both produced the same results.


The 2_CreateParentDisks finished well. SQL, ADK and ADKPE were installed fine. (Screenshot)


According to the 2_CreateParentDisks script SCVMM was installed as well. But after logging into DC after the 3_Deploy script, it seems like VMM was not installed at all. Neither the VMM Files are located at "C:\Program Files", nor does the "get-service *vmm* command indicate any sign of VMM being there. (other Screenshot)


Do you have any idea why?

Manually running the 3_SCVMM_Install via the DC-Tools Disk didn't work (the Script finishes way to fast).


You can find my Log file for the 2_CreateParentDisks step attached (it states that VMM was installed after 1.04 Minutes)


Sorry for my delayed response,  but I was given other tasks.


Regards

Marcel

________________________________
Von: Jaromir Kaspar <notifications@github.com>
Gesendet: Freitag, 18. Januar 2019 16:05:50
An: Microsoft/WSLab
Cc: Mischo, Marcel; Author
Betreff: Re: [Microsoft/WSLab] SCVMM - Installing ADK(1709) gets stuck - how to install it manually (#235)


It looks like only Windows Server 2016 is affected. In my Win10 machine all works well. I tried it in Windows Server 2016 and it did not succeed.

**Comment by jaromirk** [comment]
There are 2 issues. First is ADK is not installed if Windows Server 2016 is used as host. Second is that SCVMM refuses to install on German Windows (as Database is not accessible for some reason)
