### ISSUE TITLE
Configuration of DHCP-server

### ISSUE THREAD

**Issue by Robert-LTH** [microsoft/WSLab#250]
"NOTE: In 17744 is a bug, so during deployment process DC creation takes forewer. Workaround is to just log in as corp\Administrator to DC and it magically finishes."

When using 17763.253.190108-0006.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso to create the DC I had to login to finish the configuration of the DHCP-server before the process continued.

The problem occurs in the script 2_CreateParentDisks.ps1

$LabConfig=@{
        DomainAdminName='LabAdmin';                  
        AdminPassword='P@ssw0rd!';                   
        Prefix = 'PLSLab-';                           
        SwitchName = 'LabSwitch';                    
        SecureBoot=$true;                            
        DCEdition='4';                               
        InstallSCVMM='No';                           
        AdditionalNetworksInDC=$false;               
        DomainNetbiosName="test";                    
        DomainName="test.lab";                       
        DefaultOUName="Workshop";                    
        AllowedVLANs="1-10";                         
        Internet=$true;                              
        SkipHostDnsAsForwarder=$true;                
        CustomDnsForwarders=@("8.8.8.8","1.1.1.1");  
        PullServerDC=$true;                          
        ServerISOFolder="..\ISO";                    
        ServerMSUsFolder="..\MSU";                   
        EnableGuestServiceInterface=$true;           
        DCVMProcessorCount=2;                        
        DHCPscope="10.0.0.0"                         
        DCVMVersion="8.0"                            
        AdditionalNetworksConfig=@();                
        VMs=@();                                     
    }
Missunderstood the process and tried to create my own DC. I later discovered that the kit creates its own DC and thats the one which waits for the configuration of the DHCP-server
$LABConfig.VMs += @{
            VMName = "DC01" ;
            Configuration = 'Simple' ;                    
            ParentVHD = 'Win2016Core_G2.vhdx';         
            SSDNumber = 0;                             
            SSDSize=800GB ;                            
            HDDNumber = 1;                            
            HDDSize= 40GB;                             
            MemoryStartupBytes= 512MB;                
            AddToolsVHD = $true;
            Unattend='DjoinBlob';
            DisableWCF=$true;
            CustomPowerShellCommands = "New-Item -Name Temp -Path c:\ -ItemType Directory"

        }

**Comment by jaromirk** [comment]
Hi Robert, thank you for posting the issue. I need to review that dhcp configuration. I might try newer DSC package. Let me take a look into it.

**Comment by jaromirk** [comment]
I did check if newer DSC package exists for DHCP and WSLab is using the latest one. Not sure what's causing the issue. I did not find any clue.
