### ISSUE TITLE
DC was not imported successfully

### ISSUE THREAD

**Issue by mdano01** [Microsoft/WSLab#262]
Issue just started where the WSLabs Deploy script no longer works correctly. Any time Deploy.ps1 is ran the following error occurs and is logged . I tried a completely fresh setup us WSLabs and get the same results on multiple systems.

    Directory: C:\NewLabs\scripts\LAB

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        4/17/2019   9:47 AM                VMs
Looking for Tools Parent Disks
	 Tools parent disk C:\NewLabs\scripts\ParentDisks\tools.vhdx found
Looking for DC to be imported
DC was not imported successfully Press any key to continue ...
Press enter to continue ...

**Comment by jaromirk** [comment]
Weird, can you naviflgate to lab\DC and check if vhdx and config files are there? 2_createparentdisks.ps1 finished without errors?

**Comment by mdano01** [comment]
I checked both setups and the 2_createparentdisks.ps1  file ran clean with out errors. On my original system the lab\DC vhdx and config files were all there. On the reinstallation I noticed the VHDX file did not have the DC name it had the random GUID name. I deleted the files and reran the scripts which seem fine now the DC is now being deployed from the fresh setup. I'm not sure what happened to my original WSLab setup since I've been using it for about 2 weeks without issue running some testing with AD. So original setup is broken but after rerunning the script the new setup is fixed.

**Comment by jaromirk** [comment]
Looks like DC was deleted. Or createparentdisks did not create it successfully (it uses convert-windowsimage and it creates temporary vhd with guid in name). Anyway, are you happy with WSLab?

**Comment by jaromirk** [comment]
Or maybe you ran 2_createparentdisks and it wiped DC, but you canceled it so new DC was not created? I need to double check if it cleans DC files or not.

**Comment by mdano01** [comment]
WSLabs works great for dev testing and learning. It may be possible that I ran the 2_createparentdisks since I was adding a win2019 server to the lab. Everything is work again now.

**Comment by jaromirk** [comment]
You can add 2019 vhds (if any other vhd) by running createparentdisk.ps1 from parent disks folder. Ok, ill close this issue.

**Comment by Theofried** [comment]
@jaromirk ,
I have had the same error. 
So I exchanged expand-archive with Microsoft.PowerShell.Archive\Expand-Archive
Now it works well!

**Comment by jaromirk** [comment]
Fixed, happy? :) THX for heads up!
