### ISSUE TITLE
VM data location in Cluster Sets

### ISSUE THREAD

**Issue by yukakoe** [microsoft/WSLab#279]
Hi Jaromirk, 

Thank you for the awesome lab!  I like that it's so easy to setup the environment.  
I tried out Cluster Sets scenario, and I noticed that the VM data is placed in Cluster master's InfraSOFS (\\MC-SOFS), but the docs (https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/cluster-sets) places them in each member clusters' InfraSOFS (ex. \\CL1-SOFS).  Is it a mistake or is it intentional?  If there are different usages for these InfraSOFSs, I would like to know the difference.    

Thanks!!

**Comment by jaromirk** [comment]
Meh, I spotted this issue after 17 days! Sorry! Ill reach out to John Marlin. But I think it should be placed in infra sofs as it would deny its purpose to place it on infra sofs.

**Comment by yukakoe** [comment]
No problem!  
Thank you for looking into it, and I'll wait for the conclusion.  :)

**Comment by jaromirk** [comment]
Hello, I talked today with main dev of Cluster Sets and it should be placed on \\MC-SOFS (makes sense :) )

**Comment by yukakoe** [comment]
Thank you, Jaromir!


On Feb 6, 2020, at 12:02 AM, Jaromir Kaspar <notifications@github.com> wrote:

﻿

Hello, I talked today with main dev of Cluster Sets and it should be placed on \MC-SOFS (makes sense :) )
