### ISSUE TITLE
Secure copy takes a long time

### ISSUE THREAD

**Issue by jonaskul** [microsoft/WSLab#298]
When deploying SDN Express to VMM it uses over a day to copy the templates. You have any idea why? The whole lab is running from a NVMe.

![image](https://user-images.githubusercontent.com/47973445/70375159-ef114b00-18fa-11ea-8421-6ac65711d60e.png)

**Comment by jonaskul** [comment]
And then it fails, this is the second time I am trying.

**Comment by jaromirk** [comment]
this scenario is created by @AndreasSobczyk. Mine is just S2D and SDN. @AndreasSobczyk, do you have an idea here?

**Comment by jonaskul** [comment]
Thank you. I may also add that I had to change the names of the image files (swap what is Core and not) or the DC would install as core. It did that correctly but I had no way to use the VMM Console. Or is that by design?

**Comment by jaromirk** [comment]
Like during 2_createparentdisks? Maybe LabConfig is bit off. To be honest, I did not validate these scenarios. You may want to give try to this one https://github.com/microsoft/WSLab/tree/master/Scenarios/S2D%20and%20SDN - but I'm struggling with making Windows Admin Center work.

**Comment by jonaskul** [comment]
Yes, during createparentdisk. I have already used the Scenarios for making working S2D with the cluster manager. Also fully got SDN working with the SDN with WAC scenario that @AndreasSobczyk made. We will start migrating our production S2D to VMM 2019 in Q1 so it would be fun to test out some new features first. Are you using much DSC with these scenarios?

**Comment by jaromirk** [comment]
cool. I do use DSC just for DC creation. I have some vmm Scenarios - like this one https://github.com/microsoft/WSLab/tree/master/Scenarios/S2D%20and%20SCVMM%202019

**Comment by jonaskul** [comment]
> cool. I do use DSC just for DC creation. I have some vmm Scenarios - like this one https://github.com/microsoft/WSLab/tree/master/Scenarios/S2D%20and%20SCVMM%202019

Very nice have to look into DSC more. Will definitely have a go at that Scenario and maybe take the SDN from there.

Will close and comment this and then open a new one if I have problems with that one. Thank you!
