### ISSUE TITLE
Timeout when not enough RAM

### ISSUE THREAD

**Issue by GeedieZ** [microsoft/WSLab#300]
I've run WSLab while other VM's in Hyper-V were running and it timeouted on me when "Starting DC"

```
Starting DC
Start-VM : Nie można uruchomić maszyny „DC”.
Nie można przydzielić 2048 MB pamięci RAM: Zasoby systemowe nie wystarczają do ukończenia żądanej usługi. (0x800705AA).
Nie można uruchomić maszyny wirtualnej „DC”. (Identyfikator maszyny wirtualnej: B491206A-6188-4932-8B05-97D74D66B3A9)
Maszyna wirtualna „DC” nie może przydzielić 2048 MB pamięci RAM: Zasoby systemowe nie wystarczają do ukończenia żądanej usługi. (0x800705AA) (identyfikator maszyny wirtualnej: B491206A-6188-4932-8B05-97D74D66 B3A9).
At C:\temp\WSLab\2_CreateParentDisks.ps1:882 char:19
+             $DC | Start-VM
+                   ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.StartVM
```
It's in Polish but surely you get the idea. It's saying that there are not enough resources available to complete the service

Maybe the script could check if there's enough RAM in Hyper-V before deploying the VMs?

**Comment by jaromirk** [comment]
I understand polish quite well as when I was small, we were able to catch polish TV broadcasting :). We can do try-catch when starting VM. Will try to look into it. In meanwhile you can close outlook and try again :-D.

**Comment by jaromirk** [comment]
Fixed, thx!
