### ISSUE TITLE
NumberOfLogicalProcessors not correctly incremented

### ISSUE THREAD

**Issue by dcfou** [microsoft/WSLab#322]
On the "3_Deploy.ps1", Line 717 throws errors
Get-CimInstance -ClassName "win32_processor" | Select-Object NumberOfLogicalProcessors | ForEach-Object { $global:NumberOfLogicalProcessors += $_ }

This one works fine for me
Get-CimInstance -ClassName "win32_processor" | Select-Object -ExpandProperty NumberOfLogicalProcessors | ForEach-Object { $global:NumberOfLogicalProcessors += $_ }

**Comment by jaromirk** [comment]
@machv why not just (Get-CimInstance -ClassName "win32_processor").NumberOfLogicalProcessors ?Why counting it like this?

**Comment by machv** [comment]
@jaromirk The reason for a foreach loop is because of multiple CPUs.

@dcfou Thank you for finding this out, I will push fix to the repo.
