### ISSUE TITLE
Error when running the CreateParentDisk script

### ISSUE THREAD

**Issue by LiviuMosoiu888** [microsoft/WSLab#329]
Hello, I hope that you are doing well.

I have the following error showing when the script reaches Starting DC

 Starting DC
	 Configuring DC using DSC takes a while.
	 	 Initial configuration in progress. Sleeping 250 seconds
PS>TerminatingError(Invoke-Command): "Cannot validate argument on parameter 'VMId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again."
Invoke-Command : Cannot validate argument on parameter 'VMId'. The argument is null or empty. Provide an argument that 
is not null or empty, and then try the command again.
At E:\WSLab\scripts\2_CreateParentDisks.ps1:905 char:46
+                 $test=Invoke-Command -VMGuid $DC.id -ScriptBlock {Get ...

Can you please let me know what am I doing wrong?

Many thanks and best regards

**Comment by LiviuMosoiu888** [comment]
Hello.

Also, I seem to get this error when running the 1_Prereq.ps1 file:

WARNING: Cannot access 'https://ci.appveyor.com/nuget/docker-powershell-dev'. Are you missing 'Credential' parameter in
 the cmdlet?
WARNING: Unable to resolve package source 'https://ci.appveyor.com/nuget/docker-powershell-dev'.

Any idea on why this is happening?

Best regards and many thanks

**Comment by LiviuMosoiu888** [comment]
Sorry, my bad. I had an additional PackageSource from Docker, and PS was trying to use that one. I have unregistered the PackageSource and all seems to be working now for step 1. Will check step 2 and see how it goes.

Many thanks

**Comment by jaromirk** [comment]
I just saw this issue :). Glad it solved itself. Let me know if you will come across something else!
