### ISSUE TITLE
Can't go pass Active Directory start

### ISSUE THREAD

**Issue by Fazlec** [microsoft/WSLab#339]
Hi Jaromir,
 I am trying to use your script on my laptop and haven't change anything . I am getting stuck at "Waiting for Active Directory on WSLab-DC to be Started." . Would you please suggest how can i solve the issue ?
thanks,
Fazle
![WSLab Issue](https://user-images.githubusercontent.com/53973079/84834806-3d1caf00-b000-11ea-8bf5-070e0b64d8f1.JPG)

**Comment by jaromirk** [comment]
Well, this is weird! Can you share logs (result from 2_createParentDisks.ps1)? 
![image](https://user-images.githubusercontent.com/9829838/84899103-8294b700-b0a8-11ea-8398-af63c0f37b89.png)

**Comment by Fazlec** [comment]
Thanks for your reply .Here I have attached the log .Please check 
[CreateParentDisks.log](https://github.com/microsoft/WSLab/files/4793241/CreateParentDisks.log)

**Comment by jaromirk** [comment]
well, something weird happened "Files found in E:\WSLab\LAB\DC\. DC Creation will be skipped" ... It actually did not create DC. Did you just run first script, then second? Second is supposed to create DC... maybe it failed and you tried it once again?

**Comment by jaromirk** [comment]
The fastest way is to start from scratch, and after running first script just copy Win2019 VHDs from old folder to new (just parent disks folder). This will speed up parent disk creation as it will be skipped :). So just DC will be created...

**Comment by Fazlec** [comment]
I have started fresh  after failing to install the DC just to find out it's failing again . I have attached new log .please check.
[CreateParentDisks.log](https://github.com/microsoft/WSLab/files/4796471/CreateParentDisks.log)
[Prereq.log](https://github.com/microsoft/WSLab/files/4796472/Prereq.log)

**Comment by jaromirk** [comment]
please ping me at jaromirk@microsoft.com. We can schedule teams meeting to troubleshoot today. thank you!

**Comment by jaromirk** [comment]
Weird!
Mount-WindowsImage : Incorrect function

what module do you have?

![image](https://user-images.githubusercontent.com/9829838/84992170-dc988980-b147-11ea-8030-edcd5edec0a1.png)

**Comment by jaromirk** [comment]
Lab was hydrated on external disk with exFAT filesystem. We need to add check for volume filesystem (must be NTFS or ReFS).

**Comment by jaromirk** [comment]
added checks for ntfs/refs in latest commit.
