### ISSUE TITLE
WSLab/Scenarios/S2D Tools/Restart-S2DCluster/

### ISSUE THREAD

**Issue by dafoyiming** [microsoft/WSLab#342]
At C:\Users\LabAdmin\Desktop\RestartCluster.ps1:13 char:40
+ foreach ($ClusterNode in $ClusterNodes){
+                                        ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndCurlyBrace

**Comment by jaromirk** [comment]
Thx. Fixed! I also added optional storage maintenance mode...
