### ISSUE TITLE
Attempting to upgrade the 2016 S2d cluster to 2019 fails

### ISSUE THREAD

**Issue by thefeds-nau** [microsoft/WSLab#346]
Hello, I am wondering how I can go about testing the upgrade path from 2016 S2D to 2019. I attempted already, but received "safe_os phase error" on first reboot. I turned off secure boot to no help.  I know i can just deploy a 2019 Farm, but i am trying to test this prior to upgrading our physical S2D nodes.
Thank you

**Comment by jaromirk** [comment]
Hi, you are doing inplace upgrade inside wslab?

**Comment by thefeds-nau** [comment]
Yes. We have three 7 node windows 2016 S2D Hyper converged clusters. I would like to step through an upgrade scenerio with wslab prior to attempting on our physical nodes.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaromirk** [comment]
well I did not try it with inplace :(. Try increasing amount of RAM. by default there is 512 - for SETUP it;s not enough for sure.

**Comment by thefeds-nau** [comment]
Yes, I will try that. The other thing I am going to try is using the Windows Server 2019 1909 image for upgrade. I deployed a 3 node Lab last night using all 2019 1909 image and the storage built with no errors.

Fed Gallardo
Senior System Administrator
Northern Arizona University
928.523.2963

**Comment by jaromirk** [comment]
well, you should use 1809 aka RS5. 1909 is Semi-Annual Channel only. just download latest media, it contains June Cumulative update already.

**Comment by jaromirk** [comment]
also join slack, there is huge pile of people that might already do inplace. and we can discuss node reinstall there.

**Comment by thefeds-nau** [comment]
Ok, mind sending me an invite?

Fed Gallardo
Senior System Administrator
Northern Arizona University
928.523.2963

**Comment by jaromirk** [comment]
done
