### ISSUE TITLE
Can not start VMs in Scenario S2D Hyperconverged

### ISSUE THREAD

**Issue by JoernHenrichs** [microsoft/WSLab#353]
I'm running WSlab with the Scenario on Windows 10, latest Version 2004 (Build 19041.330).
Creation of Lab was successful, i haven't seen any error.
When i try to start a Test- or self created VM i get:

"Virtual Machine TestVMMyVolumeonHDDs1_1' failed to start.
'TestVMMyVolumeonHDDs1_1' failed to start. (Virtual machine ID D2296854-A16F-40AC-99CB-8CE953744865)
The Virtual Machine Management Service failed to start the virtual machine 'TestVMMyVolumeonHDDs1_1' because one of the Hyper-V components is not running (Virtual machine ID D2296854-A16F-40AC-99CB-8CE953744865)."
and
"Cluster resource 'Virtual Machine TestVMMyVolumeonHDDs1_1' of type 'Virtual Machine' in clustered role 'TestVMMyVolumeonHDDs1_1' failed. The error code was '0x80004005' ('Unspecified error').
Based on the failure policies for the resource and role, the cluster service may try to bring the resource online on this node or move the group to another node of the cluster and then restart it.  Check the resource and group state using Failover Cluster Manager or the Get-ClusterResource Windows PowerShell cmdlet."

I've no Idea what is missing, all Services are running  ...

**Comment by jaromirk** [comment]
Hi, is nested virtalization enabled? you can either specify it in labconfig  (nestedvirt=$true) or after vms are created, you can configure it with Posh (I think set-vmprocessor - exposevirtualizationextension $true (sorry, on phone now 🙂)

**Comment by jaromirk** [comment]
run this on host when vms (s2d1,s2d2,s2d3 and s2d4 are shut) Set-VMProcessor -ExposeVirtualizationExtensions $true -VMName *s2d* ... after boot you should be fine (unless you have AMD processor. But this will get fixed in some insider preview as already announced)

**Comment by JoernHenrichs** [comment]
Hi,
thanks for your reply.
I ran the command "...-ExposeVirtualizationExtensions.."  on my Host for the S2D* Machines and that didn't help.
I'll redeploy the Lab with modified labconfig File in the next days, when there is time to play with WSlab again.

Thank you for this amazing scripting! :-)
