### ISSUE TITLE
Prereq fails at download diskspd

### ISSUE THREAD

**Issue by hhulsman** [microsoft/WSLab#368]
Hi, wslab is awesome!

Now I got stuck with this:

Prereq.ps1 line 163 contains:
$downloadurl = $webcontent.BaseResponse.ResponseUri.AbsoluteUri.Substring(0,$webcontent.BaseResponse.ResponseUri.AbsoluteUri.LastIndexOf('/'))+($webcontent.Links | where-object { $_.'data-url' -match '/Diskspd.*zip$' }|Select-Object -ExpandProperty "data-url")

After executing, $downloadurl contains just "https://github.com/microsoft". The where-object clause returns empty

**Comment by jaromirk** [comment]
@machv will fix it - it;s his regex ;D ... You can safely ignore it since it's just example tool that is added to tools disk (it just demonstrates you can have some tools there). Thank you for raising this issue and thank you for using WSLab!

**Comment by jaromirk** [comment]
hmm, looks like aka.ms/diskspd changed path to github... then it's broken. Let me harcode zip.

**Comment by jaromirk** [comment]
OK, fixed. Thank you!

**Comment by hhulsman** [comment]
Thanks!
