### ISSUE TITLE
I want Windows 2004

### ISSUE THREAD

**Issue by webmasterfcn** [microsoft/WSLab#388]
$LabConfig.VMs += @{ VMName = 'Management' ; Configuration = 'Simple' ; ParentVHD = 'Win1019H1_G2.vhdx'  ; MemoryStartupBytes= 1GB ; MemoryMinimumBytes=1GB ; AddToolsVHD=$True ; DisableWCF=$True ; EnableWinRM=$True ; vTPM=$True} is windows 10 1903

So what must i define to use windows 2004 (the may update)
Is there a table for definitions?

**Comment by jaromirk** [comment]
simply change vhd name "ParentVHD = 'Win1019H1_G2.vhdx' " to latest version. you just need to have this vhd in parent disk folder. you can create vhd using createparentdisk.ps1 located in same folder.
