### ISSUE TITLE
Server 2016 fails to parse Unattend.xml

### ISSUE THREAD

**Issue by radugrecu** [microsoft/WSLab#389]
I couldn't get 2_CreateParentDisks.ps1 to complete because the DC wouldn't parse the Unattend.xml file.

This is because the <SupportProvider> element (within [specialize --> Microsoft-Windows-Shell-Setup --> OEMInformation]) is not valid for Server 2016.

**Comment by jaromirk** [comment]
Got it! Will test and máje it only for 2019+

**Comment by jaromirk** [comment]
fixed in latest release. I just merged it. Please give it a try and let me know.

**Comment by radugrecu** [comment]
Works great - thanks.
