### ISSUE TITLE
install telegraf folder name bug

### ISSUE THREAD

**Issue by mikumich** [microsoft/WSLab#408]
In Scenario S2DandGrafana there is a bug in the region push telegraf agent to nodes.

After updating the link for Telegraf to:
`Invoke-WebRequest -UseBasicParsing -Uri https://dl.influxdata.com/telegraf/releases/telegraf-1.16.2_windows_amd64.zip -OutFile "$env:USERPROFILE\Downloads\telegraf.zip"`
the script downloaded file telegraf.zip with a `telegraf-1.16.2` folder inside.

Then while executing part of script:
`#expand telegraf
Expand-Archive -Path "$env:USERPROFILE\Downloads\Telegraf.zip" -DestinationPath "$env:temp" -Force`
and:
`invoke-command -session $sessions -scriptblock {
    Start-Process -FilePath "$env:ProgramFiles\telegraf\telegraf.exe" -ArgumentList "--service install" -Wait
    Start-Service Telegraf
}`
we cannot find path: 'C:\Users\LabAdmin\AppData\Local\Temp\Telegraf' because it does not exist.

You have to change folder `telegraf-1.16.2` to `telegraf` inside the temp folder like it does for zip's names.

**Comment by jaromirk** [comment]
ah, got it. They used to have just executables inside zip. Now it's in the folder. Will fix it! THX!

**Comment by jaromirk** [comment]
I updated binaries with latest and bit fixed the code :). I pushed it to Dev. Please take a look and give it a try https://github.com/microsoft/WSLab/tree/dev/Scenarios/S2D%20and%20Grafana THX! Jaromir
