### ISSUE TITLE
Need to specify TLS 1.2 in script

### ISSUE THREAD

**Issue by systeminsecure** [microsoft/WSLab#414]
Hi Jaromir.

First of all, thank you for such a great set of scripts!

I executed DownloadLatestCUs.ps1, and I ran into a problem where Powershell defaults to an older version of TLS while trying to download NuGet. This is easily solved by adding the following line at the top of the script:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Do you think you could add it to the top of this script in your next release?  There may be other scripts that could use it too.

**Comment by jaromirk** [comment]
OK! Will fix it right away!

**Comment by jaromirk** [comment]
Hmm, looks like it's bit more complicated to detect it properly.

**Comment by jaromirk** [comment]
OK, it's setting tls just for process, so I simply added this line :). THX For opening the issue. It's fixed now.

**Comment by systeminsecure** [comment]
Thanks Jaromir. Keep up the good work!
