### ISSUE TITLE
AKS On Azure Stack HCI

### ISSUE THREAD

**Issue by a1tan** [microsoft/WSLab#419]
Hi,
When I try to run AZSHCI and Kubernetes Scenario on an Azure VM(Windows Server 2019), I am getting below error on load balancer setup phase. Is there anything I can do to walk around this one?

![image](https://user-images.githubusercontent.com/47588489/103477749-b7f9bb80-4dd2-11eb-9a34-5c87576296fc.png)

**Comment by jaromirk** [comment]
Hi, looks like it is broken in AKS module, not wslab. I need to test it more. Can you create an issue in AKS github?

**Comment by jaromirk** [comment]
OK, problem on my side. Azure Stack HCI needs to be registered first (this changed after GA), so it can run VMs as HA resources

**Comment by jaromirk** [comment]
I just fixed it in Dev branch. https://github.com/microsoft/WSLab/tree/dev/Scenarios/AzSHCI%20and%20Kubernetes

**Comment by jaromirk** [comment]
Merged to master
