### ISSUE TITLE
Cannot be running in root folder

### ISSUE THREAD

**Issue by jjindrich** [microsoft/WSLab#420]
I was trying to run lab in D:\ and if failed. This bug was found in scenario "AzSHCI and Kubernetes"

**Comment by Haribo112** [comment]
I dont think that's a bug, Hyper-V won't use root folder because of reasons.

**Comment by jaromirk** [comment]
Yeah, I just need to add few lines to detect it and prevent script from running...

**Comment by jaromirk** [comment]
Added this check https://github.com/microsoft/WSLab/commit/8a1e69b7a7b72e943f56a0d088b4c638a0123392

**Comment by jaromirk** [comment]
all 3 scripts will return this error if running in root folder.
![image](https://user-images.githubusercontent.com/9829838/107579430-6c1e0b80-6bf5-11eb-81a2-953ce7412ade.png)
